version: "3.8"

services:
  postgres:
    image: postgres:15-alpine
    container_name: absolut_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME:-postgres}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres123}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - absolut_network

volumes:
  postgres_data:
    driver: local

networks:
  absolut_network:
    driver: bridge
