# Generated by Django 5.2.4 on 2025-07-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_statuses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(default='#005232', max_length=7, verbose_name='Цвет статуса'),
        ),
    ]
