# Generated by Django 5.2.4 on 2025-07-06 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_statuses', '0002_alter_orderstatus_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderstatus',
            name='color',
            field=models.CharField(choices=[('#005232', 'Зеленый'), ('#930009', 'Красный'), ('#643e00', 'Коричневый')], default='#005232', max_length=7, verbose_name='Цвет статуса'),
        ),
    ]
