# Generated by Django 5.2.4 on 2025-07-06 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order_statuses', '0003_alter_orderstatus_color'),
        ('packaging', '0001_initial'),
        ('services', '0001_initial'),
        ('transport', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_number', models.CharField(max_length=32, verbose_name='Номер автомобиля')),
                ('departure_datetime', models.DateTimeField(verbose_name='Дата отправки')),
                ('delivery_datetime', models.DateTimeField(verbose_name='Дата доставки')),
                ('travel_time', models.DurationField(verbose_name='Время в пути')),
                ('distance', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Дистанция (км)')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='orders/', verbose_name='Медиафайл (pdf/img)')),
                ('collector', models.CharField(max_length=70, verbose_name='Сборщик')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('packagings', models.ManyToManyField(related_name='orders', to='packaging.packaging', verbose_name='Упаковки')),
                ('services', models.ManyToManyField(related_name='orders', to='services.service', verbose_name='Услуги')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order_statuses.orderstatus', verbose_name='Статус доставки')),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='transport.transport', verbose_name='Модель автомобиля')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
