# Generated by Django 5.2.4 on 2025-07-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('packaging', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='packagings',
            field=models.ManyToManyField(related_name='orders_packagings', to='packaging.packaging', verbose_name='Упаковки'),
        ),
        migrations.AlterField(
            model_name='order',
            name='services',
            field=models.ManyToManyField(related_name='orders_services', to='services.service', verbose_name='Услуги'),
        ),
    ]
